// <auto-generated />
using System;
using GridBeyond.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace GridBeyond.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210824135631_AddMarketPriceTables")]
    partial class AddMarketPriceTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GridBeyondDatabase.Models.MarketPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MarketPriceDataSetId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MarketPriceDataSetId");

                    b.ToTable("MarketPrices");
                });

            modelBuilder.Entity("GridBeyondDatabase.Models.MarketPriceDataSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MarketPriceDataSets");
                });

            modelBuilder.Entity("GridBeyondDatabase.Models.MarketPrice", b =>
                {
                    b.HasOne("GridBeyondDatabase.Models.MarketPriceDataSet", "MarketPriceDataSet")
                        .WithMany("MarketPrices")
                        .HasForeignKey("MarketPriceDataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketPriceDataSet");
                });

            modelBuilder.Entity("GridBeyondDatabase.Models.MarketPriceDataSet", b =>
                {
                    b.Navigation("MarketPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
